export const BASE_URL = "/api/assets/"; // will be proxied in vite.config.js
export const modelFiles: string[] = [
  /////////////////////////////////////// KAYKIT
  "kaykit/arrow_teamBlue.glb",
  "kaykit/arrow_teamRed.glb",
  "kaykit/arrow_teamYellow.glb",
  "kaykit/ball.glb",
  "kaykit/ball_teamBlue.glb",
  // "kaykit/ball_teamRed.glb",
  // "kaykit/ball_teamYellow.glb",
  // "kaykit/barrierFloor.glb",
  // "kaykit/barrierLadder.glb",
  // "kaykit/barrierLarge.glb",
  // "kaykit/barrierMedium.glb",
  // "kaykit/barrierSmall.glb",
  // "kaykit/barrierStrut.glb",
  // "kaykit/blaster_teamBlue.glb",
  // "kaykit/blaster_teamRed.glb",
  // "kaykit/blaster_teamYellow.glb",
  // "kaykit/bomb_teamBlue.glb",
  // "kaykit/bomb_teamRed.glb",
  // "kaykit/bomb_teamYellow.glb",
  // "kaykit/bow_teamBlue.glb",
  // "kaykit/bow_teamRed.glb",
  // "kaykit/bow_teamYellow.glb",
  // "kaykit/button_teamBlue.glb",
  // "kaykit/button_teamRed.glb",
  // "kaykit/button_teamYellow.glb",
  // "kaykit/characer_duck.glb",
  // "kaykit/character_bear.glb",
  // "kaykit/character_dog.glb",
  // "kaykit/detail_desert.glb",
  // "kaykit/detail_forest.glb",
  // "kaykit/diamond_teamBlue.glb",
  // "kaykit/diamond_teamRed.glb",
  // "kaykit/diamond_teamYellow.glb",
  // "kaykit/flag_teamBlue.glb",
  // "kaykit/flag_teamRed.glb",
  // "kaykit/flag_teamYellow.glb",
  // "kaykit/gateLargeWide_teamBlue.glb",
  // "kaykit/gateLargeWide_teamRed.glb",
  // "kaykit/gateLargeWide_teamYellow.glb",
  // "kaykit/gateLarge_teamBlue.glb",
  // "kaykit/gateLarge_teamRed.glb",
  // "kaykit/gateLarge_teamYellow.glb",
  // "kaykit/gateSmallWide_teamBlue.glb",
  // "kaykit/gateSmallWide_teamRed.glb",
  // "kaykit/gateSmallWide_teamYellow.glb",
  // "kaykit/gateSmall_teamBlue.glb",
  // "kaykit/gateSmall_teamRed.glb",
  // "kaykit/gateSmall_teamYellow.glb",
  // "kaykit/heart_teamBlue.glb",
  // "kaykit/heart_teamRed.glb",
  // "kaykit/heart_teamYellow.glb",
  // "kaykit/hoop_teamBlue.glb",
  // "kaykit/hoop_teamRed.glb",
  // "kaykit/hoop_teamYellow.glb",
  // "kaykit/lightning.glb",
  // "kaykit/plantA_desert.glb",
  // "kaykit/plantA_forest.glb",
  // "kaykit/plantB_desert.glb",
  // "kaykit/plantB_forest.glb",
  // "kaykit/powerupBlock_teamBlue.glb",
  // "kaykit/powerupBlock_teamRed.glb",
  // "kaykit/powerupBlock_teamYellow.glb",
  // "kaykit/powerupBomb.glb",
  // "kaykit/ring_teamBlue.glb",
  "kaykit/ring_teamRed.glb",
  "kaykit/ring_teamYellow.glb",
  "kaykit/rocksA_desert.glb",
  "kaykit/rocksA_forest.glb",
  "kaykit/rocksB_desert.glb",
  "kaykit/rocksB_forest.glb",
  "kaykit/slingshot_teamBlue.glb",
  "kaykit/slingshot_teamRed.glb",
  "kaykit/slingshot_teamYellow.glb",
  "kaykit/spikeRoller.glb",
  "kaykit/star.glb",
  "kaykit/swiperDouble_teamBlue.glb",
  "kaykit/swiperDouble_teamRed.glb",
  "kaykit/swiperDouble_teamYellow.glb",
  "kaykit/swiperLong_teamBlue.glb",
  "kaykit/swiperLong_teamRed.glb",
  "kaykit/swiperLong_teamYellow.glb",
  "kaykit/swiper_teamBlue.glb",
  "kaykit/swiper_teamRed.glb",
  "kaykit/swiper_teamYellow.glb",
  "kaykit/sword_teamBlue.glb",
  "kaykit/sword_teamRed.glb",
  "kaykit/sword_teamYellow.glb",
  "kaykit/target.glb",
  "kaykit/targetStand.glb",
  "kaykit/tileHigh_desert.glb",
  "kaykit/tileHigh_forest.glb",
  "kaykit/tileHigh_teamBlue.glb",
  "kaykit/tileHigh_teamRed.glb",
  "kaykit/tileHigh_teamYellow.glb",
  "kaykit/tileLarge_desert.glb",
  "kaykit/tileLarge_forest.glb",
  "kaykit/tileLarge_teamBlue.glb",
  "kaykit/tileLarge_teamRed.glb",
  "kaykit/tileLarge_teamYellow.glb",
  "kaykit/tileLow_desert.glb",
  "kaykit/tileLow_forest.glb",
  "kaykit/tileLow_teamBlue.glb",
  "kaykit/tileLow_teamRed.glb",
  "kaykit/tileLow_teamYellow.glb",
  "kaykit/tileMedium_desert.glb",
  "kaykit/tileMedium_forest.glb",
  "kaykit/tileMedium_teamBlue.glb",
  "kaykit/tileMedium_teamRed.glb",
  "kaykit/tileMedium_teamYellow.glb",
  "kaykit/tileSlopeLowHigh_desert.glb",
  "kaykit/tileSlopeLowHigh_forest.glb",
  "kaykit/tileSlopeLowHigh_teamBlue.glb",
  "kaykit/tileSlopeLowHigh_teamRed.glb",
  "kaykit/tileSlopeLowHigh_teamYellow.glb",
  "kaykit/tileSlopeLowMedium_teamRed.glb",
  "kaykit/tileSlopeLowMedium_desert.glb",
  "kaykit/tileSlopeLowMedium_forest.glb",
  "kaykit/tileSlopeLowMedium_teamBlue.glb",
  "kaykit/tileSlopeLowMedium_teamYellow.glb",
  "kaykit/tileSlopeMediumHigh_desert.glb",
  "kaykit/tileSlopeMediumHigh_forest.glb",
  "kaykit/tileSlopeMediumHigh_teamBlue.glb",
  "kaykit/tileSlopeMediumHigh_teamRed.glb",
  "kaykit/tileSlopeMediumHigh_teamYellow.glb",
  "kaykit/tileSmall_desert.glb",
  "kaykit/tileSmall_forest.glb",
  "kaykit/tileSmall_teamBlue.glb",
  "kaykit/tileSmall_teamRed.glb",
  "kaykit/tileSmall_teamYellow.glb",
  "kaykit/tree_desert.glb",
  "kaykit/tree_forest.glb",
  ///////////////////////////////////////_FURNITURE_KIT

  // "furniturekit/Bar_Stool.glb",
  // "furniturekit/Bathroom_Cabinet_Drawe.glb",
  // "furniturekit/Bathroom_Cabinet.glb",
  // "furniturekit/Bathroom_Mirror.glb",
  // "furniturekit/Bathroom_Sink.glb",
  // "furniturekit/Bathroom_Sink_Square.glb",
  // "furniturekit/Bathtub.glb",
  // "furniturekit/Bear.glb",
  "furniturekit/Bed_Bunk.glb",
  "furniturekit/Bed_Double.glb",
  "furniturekit/Bed_Single.glb",
  // "furniturekit/Bench_Cushion_Low.glb",
  // "furniturekit/Bench_Cushion.glb",
  // "furniturekit/Bench.glb",
  // "furniturekit/Bookcase_Closed_Doors.glb",
  // "furniturekit/Bookcase_Closed_Wide.glb",
  // "furniturekit/Bookcase_Closed.glb",
  // "furniturekit/Bookcase_Open_Low.glb",
  // "furniturekit/Bookcase_Open.glb",
  // "furniturekit/Books.glb",
  // "furniturekit/Cabinet_Bed_Drawer_Tabl.glb",
  // "furniturekit/Cabinet_Bed_Drawer.glb",
  // "furniturekit/Cabinet_Bed.glb",
  // "furniturekit/Cabinet_Television_Doo.glb",
  // "furniturekit/Cabinet_Television.glb",
  // "furniturekit/Cardboard_Box_Closed.glb",
  // "furniturekit/Cardboard_Box_Open.glb",
  // "furniturekit/Ceiling_Fan.glb",
  // "furniturekit/Chair_Cushion.glb",
  "furniturekit/Chair_Desk.glb",
  "furniturekit/Chair_Modern_Cushion.glb",
  "furniturekit/Chair_Modern_Frame_Cush.glb",
  // "furniturekit/Chair_Rounded.glb",
  // "furniturekit/Chair.glb",
  // "furniturekit/Coat_Rack_Standing.glb",
  // "furniturekit/Coat_Rack.glb",
  // "furniturekit/Computer_Keyboard.glb",
  // "furniturekit/Computer_Screen.glb",
  // "furniturekit/Desk_Corner.glb",
  "furniturekit/Desk.glb",
  // "furniturekit/Doorway_Front.glb",
  // "furniturekit/Doorway_Open.glb",
  // "furniturekit/Doorway.glb",
  // "furniturekit/Dryer.glb",
  // "furniturekit/Kitchen_Bar.glb",
  // "furniturekit/Kitchen_Blender.glb",
  // "furniturekit/Kitchen_Cabinet_Corner-t2IJurty30.glb",
  // "furniturekit/Kitchen_Cabinet_Corner.glb",
  // "furniturekit/Kitchen_Cabinet_Drawer.glb",
  // "furniturekit/Kitchen_Cabinet_Upper.glb",
  // "furniturekit/Kitchen_Cabinet_Upperc.glb",
  // "furniturekit/Kitchen_Cabinet_Upperl.glb",
  // "furniturekit/Kitchen_Cabinet-jRPnkxtk8s.glb",
  // "furniturekit/Kitchen_Cabinet.glb",
  // "furniturekit/Kitchen_Coffee_Machine.glb",
  // "furniturekit/Kitchen_Fridge_Built_In.glb",
  // "furniturekit/Kitchen_Fridge_Large.glb",
  // "furniturekit/Kitchen_Fridg_Small.glb",
  // "furniturekit/Kitchen_Fridge.glb",
  // "furniturekit/Kitchen_Hood_Large.glb",
  // "furniturekit/Kitchen_Microwave.glb",
  // "furniturekit/Kitchen_Sink.glb",
  // "furniturekit/Kitchen_Stove_Electric.glb",
  // "furniturekit/Kitchen_Stove_Hood.glb",
  // "furniturekit/Kitchen_Stove.glb",
  // "furniturekit/Lamp_Round_Floor.glb",
  "furniturekit/Lamp_Round_Table.glb",
  // "furniturekit/Lamp_Square_Ceiling.glb",
  // "furniturekit/Lamp_Square_Floor.glb",
  // "furniturekit/Lamp_Square_Table.glb",
  // "furniturekit/Lamp_Wall.glb",
  // "furniturekit/Laptop.glb",
  // "furniturekit/Lounge_Chair-PImRvMqW1O.glb",
  // "furniturekit/Lounge_Chair.glb",
  // "furniturekit/Lounge_Design_Chair.glb",
  // "furniturekit/Lounge_Design_Sofa_Corn.glb",
  // "furniturekit/Lounge_Design_Sofa.glb",
  // "furniturekit/Lounge_Sofa_Corner.glb",
  // "furniturekit/Lounge_Sofa_Long.glb",
  // "furniturekit/Lounge_Sofa_Ottoman.glb",
  // "furniturekit/Lounge_Sofa.glb",
  // "furniturekit/Paneling.glb",
  // "furniturekit/Plant_Small.glb",
  // "furniturekit/Potted_Plant.glb",
  // "furniturekit/Radio.glb",
  // "furniturekit/Round_Table.glb",
  // "furniturekit/Rug_Doormat.glb",
  "furniturekit/Rug_Rectangle.glb",
  "furniturekit/Rug_Round.glb",
  "furniturekit/Rug_Rounded.glb",
  "furniturekit/Rug_Square.glb",
  // "furniturekit/Shower_Round.glb",
  // "furniturekit/Side_Table_Drawers.glb",
  // "furniturekit/Side_Table.glb",
  // "furniturekit/Speaker_Small.glb",
  // "furniturekit/Speaker.glb",
  // "furniturekit/Stairs_Corner.glb",
  // "furniturekit/Stairs_Open_Single.glb",
  // "furniturekit/Stairs_Open.glb",
  // "furniturekit/Stairs.glb",
  // "furniturekit/Stool_Bar_Square.glb",
  // "furniturekit/Table_Coffee_Glass.glb",
  // "furniturekit/Table_Coffee_Square.glb",
  // "furniturekit/Table_Coffee.glb",
  // "furniturekit/Table_Cross_Cloth.glb",
  // "furniturekit/Table_Cross.glb",
  // "furniturekit/Table.glb",
  // "furniturekit/Television_Vintage.glb",
  // "furniturekit/Television.glb",
  // "furniturekit/Toaster.glb",
  // "furniturekit/Toilet_Square.glb",
  "furniturekit/Toilet.glb",
  // "furniturekit/Trashcan.glb",
  // "furniturekit/Wall_Doorway_Wide.glb",
  // "furniturekit/Wall_Doorway.glb",
  // "furniturekit/Wall_Window.glb",
  // "furniturekit/Washer.glb",

  /////////////////////////////////////// platformerkit
  "platformerkit/Brick_Wall_High.glb",
  "platformerkit/Brick_Wall_Low.glb",
  "platformerkit/Cardboard_Box_High.glb",
  "platformerkit/Cardboard_Box_Low.glb",
  "platformerkit/Cardboard_Boxes_1.glb",
  "platformerkit/Cardboard_Boxes_2.glb",
  "platformerkit/Coin_Dollar_Sign.glb",
  "platformerkit/Coin.glb",
  "platformerkit/Flag.glb",
  "platformerkit/Grass_Platform.glb",
  "platformerkit/Island.glb",
  "platformerkit/Large_Island.glb",
  "platformerkit/Large_Rock.glb",
  "platformerkit/Medium_Island.glb",
  "platformerkit/Metal_Fence.glb",
  "platformerkit/Pallet_Broken.glb",
  "platformerkit/Pallet.glb",
  "platformerkit/Pipes.glb",
  "platformerkit/Sack_Trench_Large.glb",
  "platformerkit/Sack_Trench_Small.glb",
  "platformerkit/Small_Rock.glb",
  "platformerkit/Sofa_Large.glb",
  "platformerkit/Sofa_Small.glb",
  "platformerkit/Stone_Platform.glb",
  "platformerkit/Tree.glb",

  ///////////////////////////////////////_stairskit
  "stairskit/Stairs_Center_Short.glb",
  "stairskit/Stairs_Center.glb",
  "stairskit/Stairs_Closed_Short.glb",
  "stairskit/Stairs_Closed.glb",
  "stairskit/Stairs_Corner.glb",
  "stairskit/Stairs_Open_1.glb",
  "stairskit/Stairs_Open_Short.glb",
  "stairskit/Stairs_Open_Single.glb",
  "stairskit/Stairs_Open.glb",
  "stairskit/Stairs_Sides_Short.glb",
  "stairskit/Stairs_Sides.glb",
  "stairskit/Stairs.glb",

  ///////////////////////////////////////_woodframekit
  "woodframekit/Wood_Doorway_2.glb",
  "woodframekit/Wood_Fence_1.glb",
  "woodframekit/Wood_Fence_2.glb",
  "woodframekit/Wood_Fence_3.glb",
  "woodframekit/Wood_Fence_4.glb",
  "woodframekit/Wood_Fence_5.glb",
  "woodframekit/Wood_Floor_1.glb",
  "woodframekit/Wood_Floor_2.glb",
  "woodframekit/Wood_Floor_3.glb",
  "woodframekit/Wood_Floor_4.glb",
  "woodframekit/Wood_Floor_5.glb",
  "woodframekit/Wood_Stairs_1.glb",
  "woodframekit/Wood_Stairs_2.glb",
  "woodframekit/Wood_Tent_1.glb",
  "woodframekit/Wood_Tent_2.glb",
  "woodframekit/Wood_Window_1.glb",
  "woodframekit/Wood_Window_2.glb",
  "woodframekit/Wood_Window_3.glb",
];
